### ISSUE TITLE
Add other things you might find cluster of images

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/planetfour-terrains-guide#16]
From the beta test and looking at the site we thought we wanted to do a cluster of things you might encounter but not to mark image cluster like the spiders, baby spiders,etc.

So we'd like to add on more image:  https://www.dropbox.com/s/acut64webmwui2i/other_things_examples.png?dl=0 

![other_things_examples](https://cloud.githubusercontent.com/assets/753325/8322011/4e318836-1a61-11e5-9f67-07f746cd9172.png)

with the associated text 

Other Surface Features You Might Encounter

Although we're not explicitly looking for these types of terrains below, you might encounter them in the images you review. You can identify these and any other interesting features you find in Talk with a hashtag or you can start a collection.

If you have other thoughts of were it should go, happy to go with your suggestion

**Comment by simoneduca** [comment]
@mschwamb I'd suggest I put this after 'More Examples' section, in a section of its own. Would that suit?
