### ISSUE TITLE
Quesiton - will people know to click to make the image bigger

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/planetfour-terrains-guide#24]
hey @simoneduca - thanks for all the changes - one question came up when the team just looked at the page. Will people know to click on the images to make them bigger - should there be text on the top saying to click to enlarge the images?- you know best here, so we'll go whatever you think is best 

Thanks for everything (and the Oxford comma!)

**Comment by simoneduca** [comment]
Hi @mschwamb I'd say clicking on an object is probably the most intuitive gesture, if one wants to find out more about if. How about you give it a go as it is and if it's still an issue, I'll add the additional text?

**Comment by mschwamb** [comment]
hi @simoneduca  - sounds fine by me - I trust you on this - if people mention on Talk the images are too tiny then I'll holler - thanks for making this on such short notice.
